title: "Aaditya Naik"
email: asnaik@seas.upenn.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://seas.upenn.edu/~asnaik/" # the base hostname & protocol for your site
navigation:
  - name: About Me
    link: /#about
  - name: News
    link: /#news
  - name: Research
    link: /#research
  - name: Publications
    link: /#publications
# Build settings
markdown: kramdown
